### ISSUE TITLE
Reporte3_Implemetación_de_la_librería

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-tec-design#1]
[Reporte3_Implementacion_de_la_libreria.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-tec-design/files/14717584/Reporte3_Implementacion_de_la_libreria.pdf)

**Comment by Daisy-GonzalezLita12** [comment]
[Uploading Reporte3_Implementacion_de_la_libreria.pdf…]()

**Comment by Daisy-GonzalezLita12** [comment]
[Reporte3.pdf…]

**Comment by Daniel-Velasco-Lopez** [comment]
En base a la rúbrica, han obtenido 100 puntos de 100, felicidades.

**Comment by josealfredo79** [comment]
Aunque solamente es el diseño de la libreria...en la proxima practica se implementa...por favor...
