### ISSUE TITLE
REPORTE 3_Operaciones básicas de la base de datos

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-tec-design#2]
[R3_Operaciones_de_la_base_de_datos.pdf](https://github.com/user-attachments/files/15687475/R3_Operaciones_de_la_base_de_datos.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
